name: Compile and Test changes
on: [push]

jobs:
#  compile:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-java@v3
#        with:
#          java-version: '8'
#          distribution: 'zulu'
#      - name: Caching/Restoring Maven dependencies
#        uses: actions/cache@v3
#        with:
#          path: ~/.m2/repository
#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#          restore-keys: |
#            ${{ runner.os }}-maven-
#      - name: Maven Compile
#        run: mvn clean compile
#
#  test:
#    needs: compile
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-java@v3
#        with:
#          java-version: '8'
#          distribution: 'zulu'
#      - name: Caching/Restoring Maven dependencies
#        uses: actions/cache@v3
#        with:
#          path: ~/.m2/repository
#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#          restore-keys: |
#            ${{ runner.os }}-maven-
#      - name: Maven test
#        run: mvn test
#
#  security-check:
#    needs: test
#    runs-on: ubuntu-latest
#    permissions:
#      actions: read
#      contents: read
#      security-events: write
#
#    strategy:
#      fail-fast: false
#      matrix:
#        language: [ 'java' ]
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#      - name: Caching/Restoring Maven dependencies
#        uses: actions/cache@v3
#        with:
#          path: ~/.m2/repository
#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#          restore-keys: |
#            ${{ runner.os }}-maven-
#      - name: Initialize CodeQL
#        uses: github/codeql-action/init@v2
#        with:
#          languages: ${{ matrix.language }}
#
#      - name: Autobuild
#        uses: github/codeql-action/autobuild@v2
#
#      # Autobuild attempts to build any compiled languages  (C/C++, C#, Go, or Java).
#      # If it fails, remove it and uncomment the following three lines.
#
#      # - run: |
#      #   echo "Run, Build Application using script"
#      #   ./location_of_script_within_repo/buildscript.sh
#
#      - name: Perform CodeQL Analysis
#        uses: github/codeql-action/analyze@v2
#        with:
#          category: "/language:${{matrix.language}}"

  generate-plugin-zip:
    #needs: security-check
    runs-on: ubuntu-latest
    #if: github.ref_type == 'tag' && startsWith(github.ref_name, 'release-')
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'
      - name: Caching/Restoring Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Generate Plugin Zip
        run: mvn package
      - run: mkdir pluginZip && cp target/*.zip pluginZip/datadog-ci-integration-${{ github.ref_name }}.zip
      - uses: actions/upload-artifact@v3
        with:
          name: datadog-ci-integration-${{ github.ref_name }}
          path: pluginZip/datadog-ci-integration-${{ github.ref_name }}.zip
